FROM ubuntu:latest as base
RUN apt update
RUN apt install -y openjdk-11-jdk
RUN apt install -y maven
RUN apt install -y gnupg2
RUN apt install -y pinentry-tty
COPY pliance.key .
RUN PASSPHRASE="gUfTek93WVDnTE9ui4aGL2aefX" gpg --batch --pinentry-mode loopback --command-fd 0 --import pliance.key
RUN echo 'default-key 5269763E0884A3491BAE18B63AFABCE058F03760' > /root/.gnupg/gpg.conf
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV VERSION "2022.1.3"
WORKDIR /work
COPY settings.xml /root/.m2/settings.xml
COPY pom.xml .
RUN mvn package
COPY . .

FROM base as snapshot
RUN mvn versions:set -DnewVersion=$VERSION-SNAPSHOT
RUN mvn clean deploy
RUN touch /tmp/done

FROM base
RUN mvn versions:set -DnewVersion=$VERSION
COPY --from=snapshot /tmp/done /tmp
RUN mvn clean deploy
