package pliance.sdk;

import pliance.sdk.contracts.*;
import pliance.sdk.exceptions.*;

public interface IPlianceClient {
    // @inject: interface
	ArchiveCompanyResponse archiveCompany(ArchiveCompanyCommand command) throws PlianceApiException;
	ArchiveCompanyResponse archiveCompanyV2(ArchiveCompanyCommand command) throws PlianceApiException;
	ArchivePersonResponse archivePerson(ArchivePersonCommand command) throws PlianceApiException;
	BatchRegisterPersonResponse batchRegisterPerson(BatchRegisterPersonCommand command) throws PlianceApiException;
	ClassifyCompanyHitResponse classifyCompanyHit(ClassifyCompanyHitCommand command) throws PlianceApiException;
	ClassifyCompanyLinkResponse classifyCompanyV2Link(ClassifyCompanyLinkCommand command) throws PlianceApiException;
	ClassifyCompanyResponse classifyCompanyV2Match(ClassifyCompanyCommand command) throws PlianceApiException;
	ClassifyPersonHitResponse classifyPersonHit(ClassifyPersonHitCommand command) throws PlianceApiException;
	ViewCompanyDataQueryResult companyData(ViewCompanyDataQuery request) throws PlianceApiException;
	DeleteCompanyResponse deleteCompany(DeleteCompanyCommand command) throws PlianceApiException;
	DeleteCompanyResponse deleteCompanyV2(DeleteCompanyCommand command) throws PlianceApiException;
	DeletePersonResponse deletePerson(DeletePersonCommand command) throws PlianceApiException;
	WebhookDeleteResponse deleteWebhookDeliveryFailure(WebhookDeleteCommand command) throws PlianceApiException;
	CompanyReportQueryResult getCompanyReport(CompanyReportQuery request) throws PlianceApiException;
	GeneralReportQueryResult getGeneralReport(GeneralReportQuery request) throws PlianceApiException;
	PersonReportQueryResult getPersonReport(PersonReportQuery request) throws PlianceApiException;
	WebhookQueryResult getWebhook(WebhookQuery request) throws PlianceApiException;
	ListCompanyQueryResult listCompanies(ListCompanyQuery request) throws PlianceApiException;
	ListPersonQueryResult listPersons(ListPersonQuery request) throws PlianceApiException;
	WebhookDeliveryFailuresQueryResult listWebhookDeliveryFailures(WebhookDeliveryFailuresQuery query) throws PlianceApiException;
	PingResponse ping(PingQuery request) throws PlianceApiException;
	WebhookPokeQueryResult poke(WebhookPokeQuery query) throws PlianceApiException;
	RegisterCompanyResponse registerCompany(RegisterCompanyCommand command) throws PlianceApiException;
	RegisterCompanyV2Response registerCompanyV2(RegisterCompanyV2Command command) throws PlianceApiException;
	RegisterPersonResponse registerPerson(RegisterPersonCommand command) throws PlianceApiException;
	WebhookUpdateResponse saveWebhook(WebhookUpdateCommand command) throws PlianceApiException;
	CompanySearchQueryResult searchCompany(CompanySearchQuery request) throws PlianceApiException;
	PersonSearchQueryResult searchPerson(PersonSearchQuery request) throws PlianceApiException;
	UnarchiveCompanyResponse unarchiveCompany(UnarchiveCompanyCommand command) throws PlianceApiException;
	UnarchiveCompanyResponse unarchiveCompanyV2(UnarchiveCompanyCommand command) throws PlianceApiException;
	UnarchivePersonResponse unarchivePerson(UnarchivePersonCommand command) throws PlianceApiException;
	ViewCompanyQueryResult viewCompany(ViewCompanyQuery request) throws PlianceApiException;
	ViewCompanyV2Response viewCompanyV2(ViewCompanyQuery query) throws PlianceApiException;
	ViewPersonQueryResult viewPerson(ViewPersonQuery request) throws PlianceApiException;
	WatchlistCompanyQueryResult watchlistCompany(WatchlistCompanyQuery request) throws PlianceApiException;
	WatchlistCompanyQueryResult watchlistCompanyV2(WatchlistCompanyV2Query request) throws PlianceApiException;
	WatchlistQueryResultV2 watchlistCompanyV2Link(WatchlistCompanyV2LinkQuery request) throws PlianceApiException;
	WatchlistQueryResult watchlistPerson(WatchlistQuery request) throws PlianceApiException;
	WatchlistQueryResultV2 watchlistPersonV2(WatchlistQueryV2 request) throws PlianceApiException;
    // @inject: !interface
}
